# Generated by Django 4.2.5 on 2023-09-16 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.IntegerField()),
                ('photo', models.URLField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.client')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude_depart', models.FloatField()),
                ('latitude_depart', models.FloatField()),
                ('longitude_arrivee', models.FloatField()),
                ('latitude_arrivee', models.FloatField()),
                ('date_livraison', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat_livraison', models.BooleanField(default=False)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.livreur')),
                ('marchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_commandes.marchandise')),
            ],
        ),
    ]
