# Generated by Django 4.2.5 on 2023-09-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0006_alter_admin_id_alter_client_id_alter_livreur_id_and_more'),
        ('gestion_commandes', '0002_remove_marchandise_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_utilisateurs.livreur'),
        ),
        migrations.AlterField(
            model_name='marchandise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_marchandise/'),
        ),
    ]
