# Generated by Django 4.2.5 on 2023-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0003_alter_livraison_livreur_alter_marchandise_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='code_prise_marchandise',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='code_validation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='marchandise',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marchandise',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_marchandise/'),
        ),
    ]
