# Generated by Django 4.2.5 on 2023-09-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0004_livraison_code_prise_marchandise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchandise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_marchandise/'),
        ),
    ]
