# Generated by Django 4.2.5 on 2023-10-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0006_alter_livraison_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='code_prise_marchandise',
        ),
    ]
