# Generated by Django 4.2.5 on 2023-12-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0007_remove_livraison_code_prise_marchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='mode_livraison',
            field=models.CharField(choices=[('aerien', 'aerien'), ('terrestre', 'terrestre')], default='aerien', max_length=10),
        ),
        migrations.AddField(
            model_name='marchandise',
            name='poids',
            field=models.FloatField(null=True),
        ),
    ]
