# Generated by Django 4.2.5 on 2023-09-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0006_alter_admin_id_alter_client_id_alter_livreur_id_and_more'),
        ('gestion_commandes', '0005_alter_marchandise_photo'),
        ('gestion_notifications', '0002_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='livreur_choisi',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='livreurs_recus',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='marchandise',
        ),
        migrations.AddField(
            model_name='notification',
            name='livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_commandes.livraison'),
        ),
        migrations.AddField(
            model_name='notification',
            name='livreurs_postule',
            field=models.ManyToManyField(blank=True, related_name='notifications_postule_liste', to='gestion_utilisateurs.livreur'),
        ),
    ]
