# Generated by Django 4.2.5 on 2023-10-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0004_alter_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
    ]
