# Generated by Django 4.2.5 on 2023-12-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0007_remove_livraison_code_prise_marchandise'),
        ('gestion_notifications', '0006_remove_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='postulation',
        ),
        migrations.AddField(
            model_name='notification',
            name='livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_commandes.livraison'),
        ),
    ]
