# Generated by Django 4.2.5 on 2023-12-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0007_remove_notification_postulation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulation',
            old_name='Livraison',
            new_name='livraison',
        ),
        migrations.RenameField(
            model_name='postulation',
            old_name='Livreur',
            new_name='livreur',
        ),
        migrations.AddField(
            model_name='notification',
            name='postulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_notifications.postulation'),
        ),
    ]
