# Generated by Django 4.2.5 on 2023-12-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0010_alter_utilisateur_type_utilisateur'),
        ('gestion_notifications', '0008_rename_livraison_postulation_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='livreurs_postule',
            field=models.ManyToManyField(blank=True, related_name='livreurs_postule_liste', to='gestion_utilisateurs.livreur'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='postulation',
        ),
        migrations.AddField(
            model_name='notification',
            name='postulation',
            field=models.ManyToManyField(blank=True, related_name='Postulation_liste', to='gestion_notifications.postulation'),
        ),
    ]
