# Generated by Django 4.2.5 on 2023-09-16 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('date_derniere_connexion', models.DateField()),
                ('photo_identite', models.URLField()),
                ('photocopie_cni', models.URLField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('date_derniere_connexion', models.DateField()),
                ('photo_identite', models.URLField()),
                ('photocopie_cni', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('date_derniere_connexion', models.DateField()),
                ('photo_identite', models.URLField()),
                ('photocopie_cni', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
