# Generated by Django 4.2.5 on 2023-09-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='mot_de_passe_par_defaut', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='mot_de_passe_par_defaut', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='password',
            field=models.CharField(default='mot_de_passe_par_defaut', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='pays',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='pays',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
