# Generated by Django 4.2.5 on 2023-09-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0002_remove_admin_user_remove_client_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('photo_identite', models.URLField(null=True)),
                ('photocopie_cni', models.URLField(null=True)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='date_derniere_connexion',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='photo_identite',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='photocopie_cni',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_derniere_connexion',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='client',
            name='photo_identite',
        ),
        migrations.RemoveField(
            model_name='client',
            name='photocopie_cni',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='date_derniere_connexion',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='photo_identite',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='photocopie_cni',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='telephone',
        ),
        migrations.AddField(
            model_name='livreur',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.utilisateur'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.utilisateur'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.utilisateur'),
        ),
    ]
