# Generated by Django 4.2.5 on 2023-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0003_utilisateur_remove_admin_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_identite',
            field=models.ImageField(blank=True, null=True, upload_to='photos_identite/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photocopie_cni',
            field=models.ImageField(blank=True, null=True, upload_to='photocopies_cni/'),
        ),
    ]
