# Generated by Django 4.2.5 on 2023-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0004_alter_utilisateur_photo_identite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('client', 'Client'), ('livreur', 'Livreur')], default='client', max_length=10),
        ),
    ]
