# Generated by Django 4.2.5 on 2023-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0006_alter_admin_id_alter_client_id_alter_livreur_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
