# Generated by Django 4.2.5 on 2023-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0007_utilisateur_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='on_mission',
            field=models.BooleanField(default=False),
        ),
    ]
